# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  devcapacityapi:
    image: devcapacityapi
    build:
      context: .
      dockerfile: DevCapacityApi/Dockerfile
    environment:
      - Kafka__BootstrapServers=kafka:9093
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - kafka
    ports:
      - "5152:5152"
    